<%@ page language="java" contentType="text/html; charset=ISO-8859-1"
	pageEncoding="ISO-8859-1"%>
<%@ page import="java.io.*,java.util.*,java.sql.*"%>
<%@ page import="javax.servlet.http.*,javax.servlet.*" %>
<%@ page import="com.buyme.User" %>

<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">
<title>BuyMe</title>
</head>
<body>

<%@include file="header.jsp" %>
<%@include file="subheader.jsp" %>

<%

try
{
	//Get the database connection
	//URL of DB
	String connectionUrl = "jdbc:mysql://mydb.c1trsunp1o0n.us-east-2.rds.amazonaws.com:3306/BuyMe";
	Connection con = null;
		
	try {
		//Load JDBC driver
		Class.forName("com.mysql.jdbc.Driver").newInstance();
	} catch (InstantiationException e) {
		e.printStackTrace();
	} catch (IllegalAccessException e) {
		e.printStackTrace();
	} catch (ClassNotFoundException e) {
		e.printStackTrace();
	}
	
	try {
		//connect to DB
		con = DriverManager.getConnection(connectionUrl,"louielou", "louielou");
	} catch (SQLException e) {
		e.printStackTrace();
	}
	
	User current = (User)session.getAttribute("currentUser");
	String userName = current.getUsername();
	String from = request.getParameter("from");
	String dateTime = request.getParameter("date_time");
	
    Statement stmt = con.createStatement();	
	
	String str = "SELECT * FROM Messege WHERE `to` = '" + userName + "' AND " + 
				 "`from` = '" + from + "' AND date_time = '" + dateTime + "'";
	
	ResultSet result = stmt.executeQuery(str);
	
	result.next();
	
%>
<table  >	
<tr>	
<th>From:</th>
<td align="left"><%=from%></td>
</tr>	
<tr>
<th>Subject:</th>
<td align="left"><%=result.getString("subject")%></td>
</tr>
<tr>	
<th>Date/Time:</th>
<td align="left"><%=dateTime%></td>
</tr>
<tr>
<th>Content:</th>
<td align="left"><%=result.getString("content")%></td>
</tr>			
</table>

<%
	// show the form to send a response back only if the sender is not the BuyMe system
	// the BuyMeSystem messeges are autogenerated and should not be responded to
	
	if (!from.equals("BuyMeSystem"))
	{

%>
<form method="post" action="emailsubmit.jsp">
		<input type="hidden" name="from" value="<%=userName%>">
		<input type="hidden" name="to" value="<%=from%>">
		Subject:<br>
		<input type="text" name="subject" style="width:550px;">
		<br>Response:<br>
		<textarea rows="40" cols="90" name="content">Type your response here......</textarea><br>
		<input type="submit" value="Submit">
	</form>
<%
	}

con.close();

}

catch(Exception e){	
	out.println(e.getMessage());	
	}
%>

</body>
</html>